on:
  push:
    branches: [main]
    paths: [.trunk/trunk.yaml]

permissions: read-all

jobs:
  cache_trunk:
    name: Cache Trunk
    runs-on: ubuntu-latest
    permissions:
      actions: write

    steps:
      - name: Checkout
        uses: actions/checkout@83b7061638ee4956cf7545a6f7efe594e5ad0247 # v3

      - name: Trunk Check
        uses: trunk-io/trunk-action@b033203e937f42022e351f1313cf84123c4472df # v1
        with:
          check-mode: populate_cache_only
