---
name: renovate-config-validator

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
  workflow_dispatch:

permissions: read-all

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b # v4
      - uses: jdx/mise-action@v4
        with:
          install: true
          cache: true
      - name: Validate Renovate config
        run: mise run validate-renovate
