---
name: annotate-pr-with-trunk-issues

on:
  workflow_run:
    workflows: ['Pull Request']
    types: [completed]

jobs:
  trunk_check:
    name: Trunk Check Annotate
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3

      - name: Trunk Check
        uses: trunk-io/trunk-action@883e222ef19201ad402ef73e58101ec8186d7d54 # v1
        with:
          post-annotations: true # only for fork PRs
