---
name: annotate-pr-with-trunk-issues

on:
  workflow_run:
    workflows: ['Pull Request']
    types: [completed]

jobs:
  trunk_check:
    name: Trunk Check Annotate
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@83b7061638ee4956cf7545a6f7efe594e5ad0247 # v3

      - name: Trunk Check
        uses: trunk-io/trunk-action@b033203e937f42022e351f1313cf84123c4472df # v1
        with:
          post-annotations: true # only for fork PRs
