---
name: annotate-pr-with-trunk-issues

on:
  workflow_run:
    workflows: ['Pull Request']
    types: [completed]

jobs:
  trunk_check:
    name: Trunk Check Annotate
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b # v4

      - name: Trunk Check
        uses: trunk-io/trunk-action@bd686325615e9cf5a4ef98372ba94a472f9b5238 # v1
        with:
          post-annotations: true # only for fork PRs
